using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Newtonsoft.Json;

namespace PostsRegisterer
{
    public partial class Form1 : Form
    {
        static String noNewPosts = "لم يتم العثور علي بوستات جديدة";
        static String invalidData = "انت لم تدخل البيانات بشكل صحيح";
        static String donePostsLoader = "تم رفع الرسائل بنجاح";
        String currDisplayedId = "";
        List<Post> posts;
        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            runPythonFile("newPosts.py");
            posts = JsonConvert.DeserializeObject<List<Post>>(File.ReadAllText("new_posts.txt"));
            if (posts.Count <= 0) MessageBox.Show(noNewPosts);
            displayNextPost();
        }

        private void displayNextPost()
        {
            if (posts.Count > 0)
            {
                Post post = posts[0];
                posts.RemoveAt(0);
                pbox_postImage.Load(post.Src);
                currDisplayedId = post.Id;
            }
            else
            {
                pbox_postImage.Visible = false;
                btn_confirm.Visible = false;
                btn_skip.Visible = false;
                btn_exclude.Visible = false;
                tb_phone.Visible = false;
                tb_price.Visible = false;
                label1.Visible = false;
                label2.Visible = false;

                btn_updateComments.Visible = true;
                btn_updateComments.Enabled = true;
                btn_updateDb.Visible = true;
                btn_updateDb.Enabled = true;
                registerToFirebase(null, null);
            }
        }

        private bool runPythonFile(String filePath)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "python";
            start.Arguments = filePath;

            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)

            Process process = Process.Start(start);
            string stdError = process.StandardError.ReadToEnd();
            if (stdError.Length > 0)
            {
                MessageBox.Show(stdError);
                return false;
            }
            return true;
        }

        private void btn_skip_Click(object sender, EventArgs e)
        {
            displayNextPost();
        }

        private void btn_exclude_Click(object sender, EventArgs e)
        {
            File.CreateText(@"exclude/" + currDisplayedId);
            displayNextPost();
        }

        private void btn_confirm_Click(object sender, EventArgs e)
        {
            String phone = tb_phone.Text.ToString();
            String price = tb_price.Text.ToString();
            String message = tb_message.Text.ToString();
            if(phone.Trim().Equals("") || price.Trim().Equals(""))
            {
                MessageBox.Show(invalidData);
                return;
            }
            var res = MessageBox.Show("confirm", "متأكد من الرقم والسعر", MessageBoxButtons.YesNo);
            if (res == DialogResult.No)
                return;
            registerToFileSystem(phone, price, message);
            displayNextPost();
        }

        private void registerToFileSystem(string phone, string price, string message)
        {
            PostInfo postInfo = new PostInfo(phone, price, message);
            String json_postInfo = JsonConvert.SerializeObject(postInfo);
            System.IO.File.WriteAllText(@"posts/" + currDisplayedId, json_postInfo);
        }
        private void registerToFirebase(object sender, EventArgs e)
        {
            if (runPythonFile("postsLoader.py"))
            {
                MessageBox.Show(donePostsLoader);
            }
        }

        private void btn_updateComments_Click(object sender, EventArgs e)
        {
            if (runPythonFile("comment_toall.py")) {
                MessageBox.Show("تم الرد علي الكومنتات التي لم يتم الرد عليها تلقائيا");
            }
        }
    }
}
